# Generated by Django 3.2.7 on 2021-10-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', models.CharField(max_length=50)),
                ('intro', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('news', models.TextField()),
            ],
        ),
    ]
