# Generated by Django 3.2.7 on 2021-10-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='FeedBack',
        ),
    ]
