# Generated by Django 3.2.7 on 2021-11-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('the_feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('intro', models.TextField()),
                ('image', models.CharField(max_length=500)),
                ('news', models.TextField()),
                ('sumber', models.TextField()),
            ],
        ),
    ]
