# Generated by Django 3.2.7 on 2021-12-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHealthy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_name', models.CharField(default='', max_length=100, null=True)),
                ('comment_field', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='HealthyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=500)),
                ('image_article', models.CharField(default='', max_length=500)),
                ('deskripsi', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
