# Generated by Django 3.2.7 on 2021-10-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_advice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
