# Generated by Django 3.2.7 on 2021-10-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_advice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenthealthy',
            name='commentator_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
