# Generated by Django 3.2.7 on 2021-10-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_advice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=500)),
                ('deskripsi', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
