# Generated by Django 3.2.7 on 2021-10-26 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthy_advice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenthealthy',
            name='commentator_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
