# Generated by Django 3.2.7 on 2021-10-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_advice', '0002_healthyarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthyarticle',
            name='image_article',
            field=models.CharField(default='', max_length=500),
        ),
    ]
