# Generated by Django 3.2.7 on 2021-10-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_advice', '0002_alter_commenthealthy_commentator_name'),
        ('healthy_advice', '0002_auto_20211026_1320'),
    ]

    operations = [
    ]
