# Generated by Django 3.2.7 on 2021-10-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_advice', '0004_alter_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_field',
        ),
    ]
